# dev: First stage testing

name: First Stage, Linting
on:
  push:
    branches: [ "dev" ]

jobs:
  lint:
    name: Lint PHP files
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: isntall Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Lint Code
        run: |
          echo "Starting PHP Lint"
          find . -type f -name "*.php" ! -path "./vendor/*" -print0 \
            | while IFS= read -r -d '' file; do
                php -l "$file" || echo "Syntax error in $file"
              done
